Repository zeroplexer/ch.bfh.bti7081.s2020.blue, pull requests merged in 2020-05, with the labels that each got.

#16 Feature/#9 database connection
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  .travis.yml
  README.md
  mvnw
  mvnw.cmd
  source/README.md
  source/pom.xml
  source/src/main/java/ch/bfh/bti7081/s2020/blue/Application.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/GreetService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/MainView.java
  source/src/main/resources/application-dev.yml
  source/src/main/resources/application.properties
  source/src/main/resources/application.yml
  source/src/test/java/ch/bfh/bti7081/s2020/blue/AbstractViewTest.java
  source/src/test/java/ch/bfh/bti7081/s2020/blue/ApplicationIntegrationTest.java
  source/src/test/java/ch/bfh/bti7081/s2020/blue/MainViewIT.java
  source/src/test/resources/application.yml
Labels: backend, enhancement, persistency

#19 move frontend folder into src/main/webapp.
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  .travis.yml
  mvnw
  mvnw.cmd
  source/pom.xml
  source/src/main/webapp/src/README
  source/src/main/webapp/styles/README
  source/src/main/webapp/styles/shared-styles.css
  source/src/main/webapp/styles/vaadin-text-field-styles.css
Labels: UI, enhancement

#17 fix Travis-CI badge in `README.md`.
  README.md
Labels: bug, documentation

#20 Feature/#7 database migration scripts
  .travis.yml
  source/README.md
  source/pom.xml
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Achievement.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Challenge.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/JournalEntry.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Login.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Patient.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Reward.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Therapist.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/association/patientchallenge/PatientHasChallenge.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/association/patientchallenge/PatientHasChallengeId.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/association/patientreward/PatientAchieved.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/association/patientreward/PatientAchievedId.java
  source/src/main/resources/application-dev.yml
  source/src/main/resources/application.yml
  source/src/main/resources/db/migration/V1__create_default_schema_tables.sql
  source/src/main/resources/db/script/create_database_user_and_schemas.sql
  source/src/test/resources/application.yml
Labels: backend, documentation, enhancement, persistency

#27 WIP: add basic ui component structure using the MVP pattern
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/JournalEntry.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Login.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Therapist.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/AchievementListPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/ChallengeDetailPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/ChallengeListPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/FooterPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/HeaderPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/JournalDetailPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/JournalListPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/TherapistListPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/ChallengeService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/JournalService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/util/Beans.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/MainView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/achievement/AchievementListView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/achievement/AchievementListViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengeDetailView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengeDetailViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengeListView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengeListViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/footer/FooterView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/footer/FooterViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/header/HeaderView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/header/HeaderViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/journal/JournalDetailView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/journal/JournalDetailViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/journal/JournalListView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/journal/JournalListViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/layout/footer/FooterView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/layout/footer/FooterViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/layout/header/HeaderView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/layout/header/HeaderViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/therapist/TherapistListView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/therapist/TherapistListViewImpl.java
Labels: UI, backend

#26 Authentication Service
  source/pom.xml
  source/src/main/java/ch/bfh/bti7081/s2020/blue/Application.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Login.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Patient.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/dto/RegisterDto.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/dto/ValidationError.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/repository/LoginCrudRepository.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/repository/PatientCrudRepository.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/LoginPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/RegistrationPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/security/FrameworkIgnoringRequestCache.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/security/SecurityConfiguration.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/DatabaseUserDetailsService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/JournalService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/RegistrationService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/util/Beans.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/util/SecurityUtils.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/SecuredView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/LoginView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/LoginViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/RegistrationView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/RegistrationViewImpl.java
Labels: UI, backend, documentation, persistency

#28 feature/#5 authentication service
  source/pom.xml
  source/src/main/java/ch/bfh/bti7081/s2020/blue/Application.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Login.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Patient.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/dto/RegisterDto.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/dto/ValidationError.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/repository/LoginCrudRepository.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/repository/PatientCrudRepository.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/LoginPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/RegistrationPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/security/FrameworkIgnoringRequestCache.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/security/SecurityConfiguration.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/DatabaseUserDetailsService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/JournalService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/RegistrationService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/util/Beans.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/util/SecurityUtils.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/SecuredView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/LoginView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/LoginViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/RegistrationView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/RegistrationViewImpl.java
Labels: UI, backend, persistency

#29 add @GeneratedValue to numeric @Ids…
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Achievement.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Challenge.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/JournalEntry.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Patient.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/PostgreSQLConstants.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Reward.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Therapist.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/LoginViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/RegistrationViewImpl.java
Labels: bug, persistency

#31 Add Beans Injector for improved testability.
  source/pom.xml
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/ChallengeDetailPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/ChallengeListPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/JournalDetailPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/JournalListPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/RegistrationPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/util/BeanInjector.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/util/Beans.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/MainView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/RegistrationViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengeDetailViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengeListViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/journal/JournalDetailViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/journal/JournalListViewImpl.java
  source/src/test/java/ch/bfh/bti7081/s2020/blue/presenter/RegisterPresenterTest.java
Labels: backend, enhancement

#38 bugfix favicon redirect after successful login
  source/src/main/java/ch/bfh/bti7081/s2020/blue/configuration/SecurityConfiguration.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Achievement.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Challenge.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/JournalEntry.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Login.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Patient.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Reward.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/Therapist.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/association/patientchallenge/PatientHasChallenge.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/association/patientchallenge/PatientHasChallengeId.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/association/patientreward/PatientAchieved.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/association/patientreward/PatientAchievedId.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/dto/RegisterDto.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/dto/ValidationError.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/security/FrameworkIgnoringRequestCache.java
Labels: backend, bug

#39 add global application layout view.
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/MainView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/layout/SocialAnxietyLayout.java
Labels: UI, enhancement, question

#43 fix spelling error in SpEL configuration class.
  source/pom.xml
  source/src/main/java/ch/bfh/bti7081/s2020/blue/configuration/SpELConfiguration.java
Labels: documentation, enhancement

#45 Feature/#12 challenge view
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/dto/ChallengeDto.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/repository/ChallengeCrudRepository.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/repository/LoginCrudRepository.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/repository/PatientCrudRepository.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/domain/repository/PatientHasChallengeCrudRepository.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/ChallengeDetailPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/ChallengesPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/presenter/CurrentChallengesListPresenter.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/service/ChallengeService.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/MainView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/authentication/RegistrationViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengeDetailView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengeDetailViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengesView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/ChallengesViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/CurrentChallengesListView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/challenge/CurrentChallengesListViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/journal/JournalDetailViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/journal/JournalListViewImpl.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/landing/LandingView.java
  source/src/main/java/ch/bfh/bti7081/s2020/blue/view/layout/header/HeaderViewImpl.java
  source/src/test/java/ch/bfh/bti7081/s2020/blue/domain/repository/ChallengeCrudRepositoryIntegrationTest.java
  source/src/test/java/ch/bfh/bti7081/s2020/blue/presenter/RegisterPresenterUnitTest.java
  source/src/test/java/ch/bfh/bti7081/s2020/blue/service/ChallengeServiceUnitTest.java
Labels: UI, backend, enhancement

#54 remove postgresql as a service configuration.
  .travis.yml
Labels: bug

#55 Bugfix/#48 configure sonar cloud maven analysis
  .travis.yml
  source/pom.xml
Labels: enhancement

#52 add (and apply) apache2 license for the whole project.
  LICENSE
  README.md
Labels: documentation, enhancement
